--DEFALUT USER IDENTIFIER: tdu135585 <-- DO NOT MODIFY

--FK_CountryID
	USE "test";
	ALTER TABLE "City"
	ADD CONSTRAINT "FK_CI_CountryID" FOREIGN KEY ("FK_CountryID")
	REFERENCES "Country"("CountryID")
	ON UPDATE NO ACTION
	ON DELETE NO ACTION;
--END