--DEFALUT USER IDENTIFIER: olo135597 <-- DO NOT MODIFY

--FOREIGN KEYS PRODUCTTAG
	USE "test";
    
	 ALTER TABLE "ProductTag"
	 ADD CONSTRAINT "FK_ProductID" FOREIGN KEY ("FK_ProductID")
	 REFERENCES "Product"("ProductID")
	 On DELETE SET NULL
	 ON UPDATE NO ACTION 

	  ALTER TABLE "ProductTag"
	 ADD CONSTRAINT "FK_TagID" FOREIGN KEY ("FK_TagID")
	 REFERENCES "Tag"("TagID")
	 On DELETE SET NULL
	 ON UPDATE NO ACTION 
	
--END