--DEFALUT USER IDENTIFIER: ile135624 <-- DO NOT MODIFY

--FOREIGN KEYS ORDER
	USE "test";
	
	ALTER TABLE "Order"
	 ADD CONSTRAINT  "FK_CustomerID" FOREIGN KEY ("FK_CustomerID")
	 REFERENCES "Customer"("CustomerID")
	 ON DELETE SET NULL
	 ON UPDATE NO ACTION

	 ALTER TABLE "Order"
	 ADD CONSTRAINT  "FK_AdressID" FOREIGN KEY ("FK_AdressID")
	 REFERENCES "Adress"("AdressID")
	 ON DELETE SET NULL
	 ON UPDATE NO ACTION

	 ALTER TABLE "Order"
	 ADD CONSTRAINT  "FK_CouponID" FOREIGN KEY ("FK_CouponID")
	 REFERENCES "Coupon"("CouponID")
	 ON DELETE SET NULL
	 ON UPDATE NO ACTION
--END