--DEFALUT USER IDENTIFIER: ile135624 <-- DO NOT MODIFY

--FOREIGN KEYS ORDERITEM
	USE "test";
	
	
	 ALTER TABLE "OrderItem"
	 ADD CONSTRAINT  "FK_OrderID" FOREIGN KEY ("FK_OrderID")
	 REFERENCES "Order"("OrderID")
	 ON DELETE SET NULL
	 ON UPDATE NO ACTION
	 
	
	 ALTER TABLE "OrderItem"
	 ADD CONSTRAINT "FK_ProductID" FOREIGN KEY ("FK_ProductID")
	 REFERENCES "Product"("ProductID")
	 On DELETE SET NULL
	 ON UPDATE NO ACTION 

--END