--DEFALUT USER IDENTIFIER: ile135624 <-- DO NOT MODIFY

--FOREIGN KEYS WISHLIST
	USE "test";
	
	ALTER TABLE "Wishlist"
	 ADD CONSTRAINT  "FK_CustomerID" FOREIGN KEY ("FK_CustomerID")
	 REFERENCES "Customer"("CustomerID")
	 ON DELETE SET NULL
	 ON UPDATE NO ACTION

	 ALTER TABLE "Wishlist"
	 ADD CONSTRAINT  "FK_ProductID" FOREIGN KEY ("FK_ProductID")
	 REFERENCES "Product"("ProductID")
	 ON DELETE SET NULL
	 ON UPDATE NO ACTION
--END